name: Xquare Deployment

on:
  push:
    branches: [ main ]

jobs:
  CD:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Deploy to xquare
        uses: team-xquare/xquare-deployment-action@master
        with:
          environment: prod
          github_token: ${{ secrets.PAT }}
          access_key: ${{ secrets.ACCESS_KEY }}
          buildargs: |
            LOKI_URL=${{ secrets.LOKI_URL }}
            PROMETHEUS_URL=${{ secrets.PROMETHEUS_URL }}